version: '3'

services:
  backend:
    build:
      context: ./Back_end
      dockerfile: Dockerfile
    image: 63070165/my_backend_image:1.0
  frontend:
    build:
      context: ./Front_end
      dockerfile: Dockerfile
    image: 63070165/my_frontend_image:1.0