pipeline {
    agent any
        
        stages {
            stage('Initialize Stage') {
                steps {
                    echo 'Initial : Delete containers and images'
                     dir('Week10_lab/Lab_jenkins_dockercompose/') {
                        echo "Current path is  ${pwd()}"
                        sh 'docker-compose down --rmi all --volumes || true'
                     }
                }
            }

            stage('Build Stage'){
                steps {
                    dir('Week10_lab/Lab_jenkins_dockercompose/') {
                        echo "Current path is ${pwd()}"
                        sh "docker-compose build"
                    }
                }
            }

            stage('Push To Docker'){
                steps {
                    dir('Week10_lab/Lab_jenkins_dockercompose/') {
                        withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                            sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                        }
                        sh 'docker push 63070165/my_backend_image:1.0'
                        sh 'docker push 63070165/my_frontend_image:1.0'
                    }
                }
            }
            
            stage('Tigger to slave job'){
                steps {
                    build job: 'Slave'
                }
            }
        }
}